= Lua library for Gentoo-style versioning format
Jakub Jirutka <https://github.com/jirutka[@jirutka]>
:gh-name: jirutka/gversion.lua
:gh-branch: master
:ldoc-url: https://jirutka.github.io/gversion.lua/ldoc/

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch={gh-branch}["Build Status", link="https://travis-ci.org/{gh-name}"]
image:https://coveralls.io/repos/github/{gh-name}/badge.svg?branch={gh-branch}&service=github["Coverage Status", link="https://coveralls.io/github/{gh-name}?branch={gh-branch}"]
image:https://img.shields.io/badge/ldoc-docs-blue.svg["LDoc", link="{ldoc-url}"]
endif::env-github[]

TBD


== Installation

You can install gversion using https://luarocks.org[LuaRocks] (the Lua package manager):

    luarocks install gversion

or to get the latest development version:

    luarocks install --server=http://luarocks.org/dev gversion

Note: If you want to bootstrap development environment for running tests, read the next section.


== Set up development environment

. Clone this repository:

    git clone https://github.com/jirutka/gversion.lua.git
    cd gversion.lua

. Source file `.envrc` into your shell (or manually add `$(pwd)/.venv/bin` to your `PATH`):

    source .envrc

. Install Lua and modules for running tests into directory `.venv`:

    ./script/bootstrap

. Start hacking!

. Run tests with code coverage and linter:

    ./script/test


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
